### ISSUE TITLE
Repository needs the following

### ISSUE THREAD

**Issue by mcdonnelldean** [senecajs/q-and-a#2]
1. A readme explaining the purpose of this repository.
2. A lead maintainer @AdrieanKhisbe, this is you
3. A link and explainer on senecajs.org (please make an issue for it)
4. Perhaps an issue template (new feature on github)

I'm running on the assumption, based on the gitter chatter, the idea here is when something needs more than a quick chat in gitter the person can move it here and use issues in Q and A style.

We need to explain in the README that issues still belong on their relative repositories and this repo is more for the sort of things we are asked on Gitter. The idea being Gitter moves too fast for big questions but big questions have juicy answers.

**Comment by AdrieanKhisbe** [comment]
Added some more organisation on top on your README skeleton in the short time slot I had now ( d2c6e80)

More incoming in the afternoon
