### ISSUE TITLE
How to solve timeout error with blocking calls in seneca client?

### ISSUE THREAD

**Issue by ganeshkaila** [senecajs/q-and-a#3]
Hi,

> server.js

```
var seneca = require('seneca')();
seneca.listen({ type: 'tcp', host:'localhost' });

seneca.add({role:'some_role', cmd: 'blokcing_call'}, function (args, done) {
  rabbitmq_consumer();
  done(null, {status: 'success'}); 
});

seneca.act({role:'some_role', cmd: 'blokcing_call'}, function(err, resp) { 
  console.log('Blocking call registed.'); 
});
```

> client.js

```
var seneca = require( 'seneca' )().client({type: 'tcp', host:"localhost" });

seneca.act({role:'some_role', cmd: 'blokcing_call'}, function(err, resp) { 
console.log('Blocking call registed.'); 
});
```

I was wondering when executing blocking call .act() method of server.js is doing fine without any error messages. And, Client.js also working fine. But, Generating an error message
`
2016-03-21T10:06:04.548Z b8h8o0pm1031/1458554764529/27190/- INFO        hello   Seneca/1.3.0/b8h8o0pm1031/1458554764529/27190/- 
2016-03-21T10:06:05.214Z b8h8o0pm1031/1458554764529/27190/- INFO        client  {type:tcp,host:127.0.0.1}       
2016-03-21T10:06:15.285Z b8h8o0pm1031/1458554764529/27190/- ERROR       act     client$         OUT             -       10012   {role:message_route
r,cmd:route}    ENTRY   (anex4) -       seneca: Action  failed: [TIMEOUT:070bbglm7r17/3sanqvatiixm:10000<1458554775276-1458554765269:undefined].   
act_execute     {id:070bbglm7r17/3sanqvatiixm,gate:false,ungate:false,desc:null,time:{start:1458554765269,end:1458554775276},me Error: [TIMEOUT:070
bbglm7r17/3sanqvatiixm:10000<1458554775276-1458554765269:undefined]
    at null._onTimeout (/home/vedams/node_modules/seneca/node_modules/gate-executor/gate-executor.js:111:21)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)  
`

Can someone explain me what this error means.? How can I resolve this.? 

Thanks,
Ganesh

**Comment by mcdonnelldean** [comment]
So Seneca has a little thing inside it called a Gate Executor. The basic idea is it will respond in a given amount of time if it hears nothing back from the handler it calls. If I remember correctly it's around `3333ms` or so.

What is actually happening above is, when your handler is called, it is blocking out for longer than the default timeout. So instead of hanging your calling service it is returning an error. Use `console.log(err)` to see it.

The timeout is used by the underlying transport and can be set in a few ways, see this section of the transport README, it has a couple of code samples showing how to set it.

https://github.com/senecajs/seneca-transport#plugin-options

**Comment by ganeshkaila** [comment]
I 'm not able to understand what is happening behind the scenes. 

I 'm not saying that client is not working. But, When I started the client.js, It is showing this timeout error. 

As you said, I checked the error object. 

`{ [Error: seneca: Action  failed: [TIMEOUT:j9jvh0q6bnjg/j2dlbkrj7s3w:11111<1458566974937-1458566963819:undefined].]
  timeout: true,
  eraro: true,
  orig: 
   { [Error: gate-executor: [TIMEOUT:j9jvh0q6bnjg/j2dlbkrj7s3w:11111<1458566974937-1458566963819:undefined]]
     timeout: true,
     eraro: true,
     orig: { [Error: [TIMEOUT:j9jvh0q6bnjg/j2dlbkrj7s3w:11111<1458566974937-1458566963819:undefined]] timeout: true },
     code: 'action-timeout',
     'gate-executor': true,
     package: 'gate-executor',
     msg: 'gate-executor: [TIMEOUT:j9jvh0q6bnjg/j2dlbkrj7s3w:11111<1458566974937-1458566963819:undefined]',
     details: 
      { id: 'j9jvh0q6bnjg/j2dlbkrj7s3w',
        gate: false,
        ungate: false,
        desc: undefined,
        cb: [Function: act_done],
        fn: [Function: execute_action],
        time: [Object],
        'orig$': [Object],
        'message$': '[TIMEOUT:j9jvh0q6bnjg/j2dlbkrj7s3w:11111<1458566974937-1458566963819:undefined]' },
     callpoint: 'at null._onTimeout (/home/vedams/node_modules/seneca/node_modules/gate-executor/gate-executor.js:111:21)' },
  code: 'act_execute',
  'gate-executor': true,
  package: 'seneca',
  msg: 'seneca: Action  failed: [TIMEOUT:j9jvh0q6bnjg/j2dlbkrj7s3w:11111<1458566974937-1458566963819:undefined].',
  details: 
   { id: 'j9jvh0q6bnjg/j2dlbkrj7s3w',
     gate: false,
     ungate: false,
     desc: undefined,
     cb: [Function],
     fn: { [Function: transport_client] id: 'v5ehzx' },
     time: { start: 1458566963819, end: 1458566974937 },
     'orig$': { [Error: [TIMEOUT:j9jvh0q6bnjg/j2dlbkrj7s3w:11111<1458566974937-1458566963819:undefined]] timeout: true },
     'message$': '[TIMEOUT:j9jvh0q6bnjg/j2dlbkrj7s3w:11111<1458566974937-1458566963819:undefined]',
     message: '[TIMEOUT:j9jvh0q6bnjg/j2dlbkrj7s3w:11111<1458566974937-1458566963819:undefined]',
     pattern: '',
     instance: 'Seneca/1.3.0/2ceeisdz1vfg/1458566963121/30554/-',
     plugin: {} },
  callpoint: 'at null._onTimeout (/home/vedams/node_modules/seneca/node_modules/gate-executor/gate-executor.js:111:21)',
  seneca: true }`

For me, Nothing is helping to understand from that.

**Comment by mihaidma** [comment]
One idea might be to comment the `rabbitmq_consumer();` call and make sure that seneca works then you add it back and check if it blocks there.

To see more seneca info when debugging start the app with a flag like `node index.js --seneca.log.all`

**Comment by mcdonnelldean** [comment]
So try this,

``` js
var seneca = require('seneca')();
seneca.listen({ type: 'tcp', host:'localhost' });

seneca.add({role:'some_role', cmd: 'blokcing_call'}, function (args, done) {
  rabbitmq_consumer();
  done(null, {status: 'success'}); 
});

seneca.act({role:'some_role', cmd: 'blokcing_call'}, function(err, resp) { 
  if (err) console.log('I failed');
  else console.log(resp.status); 
});
```

It's not actually working, what is happening is `rabbitmq_consumer()` is taking so long that seneca auto responds with an error. In this case it's the execution timeout.

Change this,

```
seneca.listen({ type: 'tcp', host:'localhost' });
```

To 

``` js
seneca.listen({ type: 'tcp', host:'localhost', timeout: 5000});
```

To increase the timeout

**Comment by StarpTech** [comment]
Hi @mcdonnelldean it is possible to disable the timeout in other words the ack for this request? e.g you want to send a message to email service but you dont want that this operation can influence your initial call. Yes I could use a different transport layer but this option is usable also in other situations.
