### ISSUE TITLE
[ORG] Determine the policy for the question closing

### ISSUE THREAD

**Issue by AdrieanKhisbe** [senecajs/q-and-a#5]
Part and follow up on #2

_Make the process clear!_ :smiley: 
OpenEverything: openProcess, openRules OpenGouv

**Comment by mcdonnelldean** [comment]
Thinking about this, since it's q and a I think the best approach is,
1. Questions are labeled question
2. When you think you have answered it is labeled answered
3. The person asks more or closes
4. If the issue is still open and answered after 1 month of inactivity it is closed

**Comment by naomifeehan** [comment]
@mcdonnelldean :+1: should we also include a label for "reopened" in #4?

**Comment by mcdonnelldean** [comment]
@naomifeehanmoran yeah, makes sense alright
