### ISSUE TITLE
Troubleshooting timeouts

### ISSUE THREAD

**Issue by Wardormeur** [senecajs/q-and-a#7]
Hi,
We're facing multiples timeout issues I was wondering on the best approach:
We know that from the documentation, an action is supposed to be allowed up to 11s (http://senecajs.org/annotations/seneca.html#section-12 )
What happens when an action calls another ? The parent call time still ellapse, which makes the whole call dependant upon its own complexity (as in, for a single level depth, 11s/nb_sub-actions) ?
What's the expected behavior with nextTick ? Won't it keep the action alive ?
Thanks :+1: 

Edit : also, when a service is called with a timeout of N, with N> M, M being another service action, the determining timeout is the one from M ?

**Comment by mcdonnelldean** [comment]
So timeouts are controlled by the gate executor. You are correct, nested actions are all considered part of the one 'gated' transaction. With this in mind I would say the best approach is to reduce call complexity. This usually means break the system down into smaller microservices.

You can sort of cheat when you don't need a response by calling done() as the first line of the call. But from personal experience the most sensible optimisation in the long run was to flatten out the call depth in places.

Once place that can really benefit from this is the data aware services. Generally I would suggest caching in memory common results. Also deferring work off to non blocking calls is another great idea, blocking calls or calls that require callbacks are killers.

**Comment by mcdonnelldean** [comment]
Also bear in mind seneca sort of jives with the whole notion of eventual consistency. If a service can't answer quickly you should probably,
1. Let the service return an indeterminate result and ask it again later.
2. Increase the timeout in the case where it must wait.
3. Create a service that builds cached answers on the fly and ask it instead.

Remember that most timeout issues can be solved by simple return empty and asking again :D

**Comment by Wardormeur** [comment]
Thanks :+1:
And for external API's, the best practice would be to allow unconsitency during a certain time by queing them ?
By flattening, it means the client is actually doing the calls instead of doing internal server calls ?

**Comment by mcdonnelldean** [comment]
@Wardormeur not specifically. Flatten I generally mean if the chain to get the data is 5 calls down it may make more sense to rethink it and split into groups of functionality that make less calls.

In terms of queueing et al, it depends :D Basically the data freshness will determine how to defer in this regard. So some stuff you may just need to wait for, others can be send to a queue since you only care that they made it to the queue.
