### ISSUE TITLE
How to access header information inside seneca add

### ISSUE THREAD

**Issue by manojktechie** [senecajs/q-and-a#8]
I am trying to access the header information inside seneca add. Is it possible to access the header information without using seneca-web ?

Basically I am thinking to create oauth2 server using example https://github.com/reneweb/oauth2orize_resource_owner_password_example but instead of making http call I want to call it through seneca act. Is this possible, as I am not able to access req, res object inside seneca add

I hope i am not asking a silly question.

**Comment by mcdonnelldean** [comment]
@manoj150283 not at all.

So the header information means a couple of different things. All seneca messages have a thing attached to each message called `meta$` so if you go `msg.meta$` you get access to all of the info seneca has.

In terms of the http specific stuff. That is added explicitly by seneca-web. It basically decorates the message with this information. The only way to have it attached would be via seneca-web or a plugin you create yourself that does the same thing.

When the message is sent over http via the inbuilt transport the header information is not attached to the message. Having said that. @mirceaalexandru may be able to chime in and see if this is something we could change. Generally though the point of the inbuilt transport for http is not for REST, it's strictly for transport.

**Comment by mcdonnelldean** [comment]
To clarify, we would expect seneca-web to be used if you are building anything around http.
